language: ruby
rvm:
  - 2.1.0
before_script:
  - gem install bundler -v '= 1.5.1'
  - cp config/settings.travis.yml config/settings.yml
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database memorizr_test;'
